[2023-04-08 03:05:20,732] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-08T03:05:18.856245+00:00 [queued]>
[2023-04-08 03:05:20,740] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-08T03:05:18.856245+00:00 [queued]>
[2023-04-08 03:05:20,741] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-08 03:05:20,742] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-08 03:05:20,743] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-08 03:05:20,758] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-08 03:05:18.856245+00:00
[2023-04-08 03:05:20,763] {standard_task_runner.py:52} INFO - Started process 634 to run task
[2023-04-08 03:05:20,767] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-04-08T03:05:18.856245+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8xlsynr5', '--error-file', '/tmp/tmptjfwcx0x']
[2023-04-08 03:05:20,769] {standard_task_runner.py:80} INFO - Job 18: Subtask is_api_available
[2023-04-08 03:05:20,828] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-04-08T03:05:18.856245+00:00 [running]> on host a51dc0b874ee
[2023-04-08 03:05:20,884] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-08T03:05:18.856245+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-08T03:05:18.856245+00:00
[2023-04-08 03:05:20,887] {http.py:97} INFO - Poking: api/
[2023-04-08 03:05:20,898] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-04-08 03:05:20,900] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-08 03:05:21,117] {base.py:301} INFO - Success criteria met. Exiting.
[2023-04-08 03:05:21,135] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230408T030518, start_date=20230408T030520, end_date=20230408T030521
[2023-04-08 03:05:21,159] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-08 03:05:21,199] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
